apiVersion: v1
kind: Namespace
metadata:
  name: xxzzxzaa-dev
  labels:
    environment-id: env_c4df3915-6680-4296-9faf-a70c92252f7b
    project-id: project_abc76706-f783-48ab-852d-5015004ee7e9
    project-name: xxzzxzaa
    environment-name: dev
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
